# Generated by Django 5.0.14 on 2026-05-09 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Tugas')),
                ('description', models.TextField(verbose_name='Deskripsi Tugas')),
                ('due_date', models.DateTimeField(verbose_name='Batas Waktu (Deadline)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Kuis')),
                ('due_date', models.DateTimeField(verbose_name='Batas Waktu (Deadline)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pertanyaan')),
                ('option_a', models.CharField(max_length=200, verbose_name='Pilihan A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Pilihan B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Pilihan C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Pilihan D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Kunci Jawaban')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/', verbose_name='File Jawaban')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pengumpulan')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Nilai')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback Dosen')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assignment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mahasiswa')),
            ],
        ),
    ]
