# Generated by Django 5.0.14 on 2026-05-09 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nama Kelas')),
                ('description', models.TextField(verbose_name='Deskripsi Kelas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Pengajar')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Materi')),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('VIDEO', 'Video'), ('PPT', 'PowerPoint'), ('LINK', 'External Link')], max_length=10, verbose_name='Tipe Materi')),
                ('content_url', models.URLField(blank=True, null=True, verbose_name='Link Eksternal')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='File Materi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
        ),
    ]
